wpproject/catalog/urls.py
# coding=utf-8

from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'catalog'
urlpatterns = [
	path('', views.product_list, name="product_list"),
	# path('(?P<slug>[\w_-]+)/$', views.category, name="category"),
    url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'),
    url(r'^produtos/(?P<slug>[\w_-]+)/$', views.product, name='product'),
]

wpproject/checkout/urls.py
# coding=utf-8

from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'checkout'
urlpatterns = [
    url(
        r'^carrinho/adicionar/(?P<slug>[\w_-]+)/$', views.create_cartitem,
        name='create_cartitem'
    ),
	path('carrinho/', views.cart_item, name="cart_item"),
	path('finalizando/', views.checkout, name="checkout"),
	path('meus-pedidos/', views.order_list, name="order_list"),

]

wpproject/wpproject/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

from core import views
from catalog import views as views_catalog
from accounts import views as views_accounts
from checkout import views as views_checkout

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name='index'),
    
    path( 'entrar/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path( 'sair/', auth_views.LogoutView.as_view(template_name='index.html'), name='logout'),

    path('catalogo/', include('catalog.urls', namespace='catalog')),
    path('conta/', include('accounts.urls', namespace='accounts')),

    path('compras/', include('checkout.urls', namespace='checkout')),
   
    path('admin/', admin.site.urls),
]

wpproject/core/models.py
from django.db import models

# Create your models here.

wpproject/core/views.py
# conding=utf-8

from django.shortcuts import render
from django.http import HttpResponse

from django.views.generic import View, TemplateView, RedirectView

# def index(request):
# 	return render(request, 'index.html')

class IndexView(RedirectView):
	template_name = 'index.html'

# index = IndexView.as_view()

index = RedirectView.as_view(permanent=False, url='catalogo')

wpproject/core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{% block title %}WP-Project{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}" media="screen" />
  <link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen" />
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="" class="navbar-brand">WP-Project</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url 'index' %}">Início</a>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'catalog:product_list' %}" id="download">Categorias <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">
                {% for category in categories %}
                  <li><a href="{{ category.get_absolute_url }}">{{ category }}</a></li>
                {% endfor %}
              </ul>
            </li>
      <li>
        {# <a href="{% url 'contact' %}">Contato</a> #}
      </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Sair</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">Entrar</a></li>
            {% endif %}
            <li><a href="{% url 'checkout:cart_item' %}">Carrinho</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container">
    {% block container %}{% endblock %}
    <footer>
      <div class="row">
        <div class="col-lg-12">
          <ul class="list-unstyled">
            <li class="pull-right"><a href="#top">Voltar ao Topo</a></li>
            <li><a href="">Início</a></li>
            <li><a href="">Produtos</a></li>
          </ul>
        </div>
      </div>
    </footer>
  </div>
  <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'assets/bootstrap.min.js' %}"></script>
</body>
</html>

wpproject/core/templates/index.html
{% extends "catalog/product_list.html" %}

wpproject/core/templates/login.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Entrar | {{ block.super }}{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Entrar</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                <div class="form-group{% if form.username.errors %} has-error{% endif %}">
                  <label for="{{ form.username.auto_id }}" class="col-md-3 control-label">{{ form.username.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.username class="form-control" %}
                    {% for error in form.username.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group{% if form.password.errors %} has-error{% endif %}">
                  <label for="{{ form.password.auto_id }}" class="col-md-3 control-label">{{ form.password.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.password class="form-control" %}
                    {% for error in form.password.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Enviar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

wpproject/core/templates/pagination.html
<div class="row">
    <div class="col-md-12">
        <nav>
          <ul class="pagination">
              {% for page in paginator.page_range %}
              <li{% if page_obj.number == page %} class="active"{% endif %}><a href="?page={{ page }}{{ getvars }}">{{ page }}</a></li>
              {% endfor %}
          </ul>
        </nav>
    </div>
</div>

wpproject/core/templates/register.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Registro | {{ block.super }}{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Registro</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                {% for field in form %}
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                  <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                  <div class="col-md-9">
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                {% endfor %}
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Registrar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}