wpproject/catalog/urls.py
# coding=utf-8

from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'catalog'
urlpatterns = [
	path('', views.product_list, name="product_list"),
	# path('(?P<slug>[\w_-]+)/$', views.category, name="category"),
    url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'),
    url(r'^produtos/(?P<slug>[\w_-]+)/$', views.product, name='product'),
]

wpproject/checkout/urls.py
# coding=utf-8

from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'checkout'
urlpatterns = [
    url(
        r'^carrinho/adicionar/(?P<slug>[\w_-]+)/$', views.create_cartitem,
        name='create_cartitem'
    ),
	path('carrinho/', views.cart_item, name="cart_item"),
	path('finalizando/', views.checkout, name="checkout"),
	path('meus-pedidos/', views.order_list, name="order_list"),

]

wpproject/wpproject/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

from core import views
from catalog import views as views_catalog
from accounts import views as views_accounts
from checkout import views as views_checkout

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name='index'),
    
    path( 'entrar/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path( 'sair/', auth_views.LogoutView.as_view(template_name='index.html'), name='logout'),

    path('catalogo/', include('catalog.urls', namespace='catalog')),
    path('conta/', include('accounts.urls', namespace='accounts')),

    path('compras/', include('checkout.urls', namespace='checkout')),
   
    path('admin/', admin.site.urls),
]

wpproject/catalog/models.py
# coding=utf-8

from django.db import models
from django.urls import reverse


class Category(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['name']

    def __str__(self):
    	return self.name

    def get_absolute_url(self):
        return reverse('catalog:category', kwargs={'slug':self.slug})


class Product(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)
    category = models.ForeignKey('catalog.Category', verbose_name='Categoria', on_delete=models.DO_NOTHING)
    description = models.TextField('Descrição', blank=True)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['name']

    def __str__(self):
    	return self.name

    def get_absolute_url(self):
        return reverse('catalog:product', kwargs={'slug':self.slug})


    


    	

wpproject/catalog/views.py
# coding=utf-8

from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Product, Category

class ProductListView(generic.ListView):
	# model = Product
	queryset = Product.objects.all()
	template_name = 'catalog/product_list.html'
	context_object_name = 'products'
	paginate_by = 3




class CategoryListView(generic.ListView):

	template_name = 'catalog/category.html'
	context_object_name = 'product_list'
	paginate_by = 3

	def get_queryset(self):
		return Product.objects.filter(category__slug=self.kwargs['slug'])

	def get_context_data(self, **kwargs):
		context = super(CategoryListView, self).get_context_data(**kwargs)
		context['current_category'] = get_object_or_404(Category, slug=self.kwargs['slug'])
		return context


# def category(request, slug):
# 	category = Category.objects.get(slug=slug)
# 	context = {
# 		'current_category': category,
# 		'product_list': Product.objects.filter(category=category),
# 	}
# 	return render(request, 'catalog/category.html', context)



def product(request, slug):
    product = Product.objects.get(slug=slug)
    context = {
        'product': product,
    }
    return render(request, 'catalog/product.html', context)


product_list = ProductListView.as_view()
category = CategoryListView.as_view()

wpproject/catalog/templates/catalog/_product.html
<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <a href="{{ product.get_absolute_url }}">
            <img src="http://placehold.it/350x250" alt="" />
        </a>
        <div class="caption">
            <h2>{{ product }}</h2>
            {{ product.description|linebreaks }}
            <h4>R${{ product.price }}</h4>
            <p><a href="{{ product.get_absolute_url }}" class="btn btn-success" role="button">Detalhes</a> <a href="{% url 'checkout:create_cartitem' product.slug %}" class="btn btn-default" role="button">Adicionar</a></p>
        </div>
    </div>
</div>

wpproject/catalog/templates/catalog/category.html
{% extends "base.html" %}

{% load pagination %}

{% block title %}
    {{ current_category }} | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>{{ current_category }}</h1>
</div>
<div class="row">
    {% for product in product_list %}
        {% include "catalog/_product.html" %}
    {% endfor %}
</div>
{% pagination request paginator page_obj %}
{% endblock %}

wpproject/catalog/templates/catalog/product.html
{% extends "base.html" %}

{% block title %}
    {{ product }} | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
  <h1>{{ product }}</h1>
</div>
<div class="row">
  <div class="col-sm-4">
      <a href="#" class="thumbnail">
          <img src="http://placehold.it/350x250" alt="" />
      </a>
  </div>
  <div class="col-sm-8">
      <p class="text-right">
          <a href="{% url 'checkout:create_cartitem' product.slug %}" class="btn btn-success">Adicionar ao Carrinho</a>
      </p>
      {{ product.description|linebreaks }}
      <p class="text-right">
          <h3>R${{product.price}}</h3>
      </p>
  </div>
</div>
{% endblock %}

wpproject/catalog/templates/catalog/product_list.html
{% extends "base.html" %}

{% load pagination %}

{% block title %}
    Listagem de Produtos | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>Produtos</h1>
</div>
<div class="row">
    {% for product in products %}
        {% include "catalog/_product.html" %}
    {% endfor %}
</div>
{% pagination request paginator page_obj %}
{% endblock %}