wpproject/accounts/urls.py
# coding=utf-8

from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.index, name='index'),
    path('registro/', views.register, name='register'),
    path('alterar-dados/', views.update_user, name='update_user'),
]

wpproject/catalog/urls.py
# coding=utf-8

from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'catalog'
urlpatterns = [
	path('', views.product_list, name="product_list"),
	# path('(?P<slug>[\w_-]+)/$', views.category, name="category"),
    url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'),
    url(r'^produtos/(?P<slug>[\w_-]+)/$', views.product, name='product'),
]

wpproject/checkout/urls.py
# coding=utf-8

from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'checkout'
urlpatterns = [
    url(
        r'^carrinho/adicionar/(?P<slug>[\w_-]+)/$', views.create_cartitem,
        name='create_cartitem'
    ),
	path('carrinho/', views.cart_item, name="cart_item"),
	path('finalizando/', views.checkout, name="checkout"),
	path('meus-pedidos/', views.order_list, name="order_list"),

]

wpproject/wpproject/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

from core import views
from catalog import views as views_catalog
from accounts import views as views_accounts
from checkout import views as views_checkout

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name='index'),
    
    path( 'entrar/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path( 'sair/', auth_views.LogoutView.as_view(template_name='index.html'), name='logout'),

    path('catalogo/', include('catalog.urls', namespace='catalog')),
    path('conta/', include('accounts.urls', namespace='accounts')),

    path('compras/', include('checkout.urls', namespace='checkout')),
   
    path('admin/', admin.site.urls),
]

wpproject/accounts/models.py
# coding=utf-8

wpproject/accounts/views.py
from django.shortcuts import render
from django.http import HttpResponse

from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import View, TemplateView, CreateView, UpdateView
from django.contrib.auth import get_user_model

from django.contrib.auth.mixins import LoginRequiredMixin


class IndexView(LoginRequiredMixin, TemplateView):
	template_name = 'accounts/index.html'



User = get_user_model()

class RegisterView(CreateView):
	form_class = UserCreationForm
	template_name = 'register.html'
	model = User
	success_url = reverse_lazy('index')


class UpdateUserView(UpdateView):
	template_name = 'accounts/update_user.html'
	model = User
	fields = ['username', 'email']
	success_url = reverse_lazy('accounts:index')

	def get_object(self):
		return self.request.user


index = IndexView.as_view()
register = RegisterView.as_view()
update_user = UpdateUserView.as_view()

wpproject/accounts/templates/accounts/index.html
{% extends "base.html" %}

{% block title %}Minha Conta{% endblock %}

{% block container %}
<ol class="breadcrumb">
  <li><a href="#">Início</a></li>
  <li class="active">Minha Conta</li>
</ol>
<div class="row">
    <div class="col-md-4">
        <div class="list-group">
          <a href="{% url 'accounts:update_user' %}" class="list-group-item">Alterar Dados</a>
          <a href="#" class="list-group-item">Alterar Senha</a>
          <a href="{% url 'checkout:order_list' %}" class="list-group-item">Meus Pedidos</a>
        </div>
    </div>
    <div class="col-md-8">
        {% block accounts_container %}
            <h2>Bem vindo {{ user }}</h2>
        {% endblock %}
    </div>
</div>
{% endblock %}

wpproject/accounts/templates/accounts/update_user.html
{% extends "accounts/index.html" %}

{% load widget_tweaks %}

{% block title %}Alterar Dados{% endblock %}

{% block accounts_container %}
    <h2>Alterar Dados</h2>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Salvar</button>
              </div>
            </div>
        </fieldset>
    </form>
{% endblock %}